/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dpD5ATZRkLM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
'use client'; 

import React, { useState, useEffect } from 'react'
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { CopyIcon } from "./Icons"


const Writer = () => {
  const [text, setText] = useState('');
  const [wordCount, setWordCount] = useState(0);
  const [charCount, setCharCount] = useState(0);
  const [viewportHeight, setViewportHeight] = useState(0);
  const [timeOfDay, setTimeOfDay] = useState('Morning');


  useEffect(() => {
    // const updateViewportHeight = () => {
    //   setViewportHeight(window.innerHeight);
    // };

    // updateViewportHeight();
    // window.addEventListener('resize', updateViewportHeight);
  
    const currentHour = new Date().getHours();

    if (currentHour < 12) {
      setTimeOfDay('Morning');
    } else if (currentHour < 18) {
      setTimeOfDay('Afternoon');
    } else {
      setTimeOfDay('Evening');
    }
        
    // return () => window.removeEventListener('resize', updateViewportHeight);
  }, []);

  const handleChange = (e) => {
    const newText = e.target.value;
    setText(newText);
    setCharCount(newText.length);
    setWordCount(newText.trim().split(/\s+/).filter(word => word.length > 0).length);
  };


  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  }

  return (
      <>
        <div className="bg-muted px-6 py-4 flex justify-between items-center border-t">
          <div className="text-sm text-muted-foreground">
            <span id="word-count">{wordCount}</span> words, <span id="char-count">{charCount}</span> characters
          </div>
          <Button variant="ghost" size="icon" className="ml-auto" onClick={handleCopy}>
            <CopyIcon className="h-5 w-5" />
            <span className="sr-only">Share to email</span>
          </Button>
        </div>      
        <div className="flex-1 pt-2 pb-2 flex flex-col">
          <Textarea
            placeholder={`Good ${timeOfDay}! Let's start Writing. Once you are done click the copy button to copy the text.`}
            value={text}
            onChange={handleChange}
            className="w-full flex-1 sm:max-h-none sm:rows-auto resize-none p-4 rounded-lg border border-input focus:border-primary focus:ring-1 focus:ring-primary"
            style={{ height: `calc(${viewportHeight}px - 160px)` }}
            />
        </div>
        <div className="bg-muted px-6 py-4 flex justify-between items-center border-t">
          <div className="text-sm text-muted-foreground">
            <span id="word-count">{wordCount}</span> words, <span id="char-count">{charCount}</span> characters
          </div>
          <Button variant="ghost" size="icon" className="ml-auto" onClick={handleCopy}>
            <CopyIcon className="h-5 w-5" />
            <span className="sr-only">Share to email</span>
          </Button>
        </div>      
      </>
    );
}

export default Writer;